{
  "hash": "b7da8b04645fc6afff62bea2638012e8",
  "result": {
    "engine": "knitr",
    "markdown": "# Lista 8.1: Moderação e Mediação {.unnumbered}\n\n::: {.callout-note appearance=\"simple\" icon=false}\n## Objetivo da Lista\n\nExplore **análise de mediação** usando SEM: compreenda efeitos diretos vs indiretos, teste hipóteses de mediação e interprete modelos causais complexos. Aprenda quando uma variável **medeia** (explica como) vs **modera** (modifica quando/para quem).\n:::\n\n---\n\n## 📚 Mediação vs Moderação\n\n::: {.callout-tip}\n## Conceitos Fundamentais\n\n**Mediação** (Como? Por que?)\n- **M explica o mecanismo** entre X → Y\n- X influencia M, que influencia Y\n- \"X afeta Y **através de** M\"\n\n**Moderação** (Quando? Para quem?)\n- **M modifica a força/direção** de X → Y\n- X × M interage para afetar Y\n- \"O efeito de X em Y **depende de** M\"\n\n**Exemplo Mediação:**\n- Exercício → Bem-estar → Produtividade\n- \"Exercício aumenta produtividade *porque* melhora bem-estar\"\n\n**Exemplo Moderação:**\n- Estresse × Suporte Social → Saúde Mental\n- \"Estresse afeta saúde *diferentemente* dependendo do suporte\"\n:::\n\n---\n\n## 📦 Pacotes\n\n\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Pacotes de mediação carregados!\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n---\n\n## 📖 Contexto do Estudo\n\n::: {.callout-tip}\n## Hipótese Teórica\n\n**Variáveis:**\n- `Sociabilidade`: Escore de questionário (X)\n- `IMC1`: Índice de Massa Corporal (M - mediador?)\n- `Treinos`: Número de treinos/mês (Y)\n- `Idade`: Anos (covariável)\n\n**Hipótese:**\n\"**Sociabilidade** aumenta **Treinos**, mas esse efeito é **mediado por IMC**\"\n\nOu seja: Pessoas mais sociáveis frequentam mais a academia **porque** isso afeta seu IMC?\n:::\n\n---\n\n## 📥 Carregar Dados\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados <- read.spss(\"DADOS PATH.sav\", to.data.frame = TRUE)\nglimpse(dados)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 94\nColumns: 4\n$ Idade         <dbl> 57, 41, 29, 26, 33, 37, 26, 44, 31, 36, 30, 55, 43, 27, …\n$ IMC1          <dbl> 28.46122, 32.62609, 26.99050, 19.03602, 28.76650, 24.686…\n$ Treinos       <dbl> 108, 144, 48, 102, 123, 63, 39, 105, 6, 48, 144, 144, 11…\n$ Sociabilidade <dbl> 14, 34, 17, 20, 26, 19, 15, 32, 27, 19, 28, 9, 30, 29, 1…\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n---\n\n## 🎯 Modelo 1: IMC como Mediador\n\n### Diagrama Conceitual\n\n```\nSociabilidade → IMC1 → Treinos\n       \\________________/\n         (efeito direto c')\n```\n\n::: {.callout-note}\n## Terminologia de Mediação\n\n**Caminho a:** X → M (Sociabilidade → IMC)  \n**Caminho b:** M → Y (IMC → Treinos)  \n**Caminho c':** X → Y direto (efeito após controlar M)  \n**Caminho c:** X → Y total (sem M no modelo)\n\n**Efeito Indireto:** a × b  \n**Efeito Total:** c = c' + (a × b)\n\n**Mediação completa:** c' = 0 (todo efeito via M)  \n**Mediação parcial:** c' ≠ 0 (parte do efeito é direto)\n:::\n\n---\n\n### Especificar Modelo\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_med1 <- \"\n  # Regressões\n  Treinos ~ c_*Sociabilidade + b*IMC1\n  IMC1 ~ a*Sociabilidade\n  \n  # Efeitos calculados\n  Indireto := a*b\n  Total := a*b + c_\n\"\n```\n:::\n\n\n\n\n\n\n\n\n---\n\n### Ajustar com Bootstrap\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_med1 <- sem(\n  modelo_med1,\n  data = dados,\n  se = \"bootstrap\",\n  bootstrap = 500\n)\n```\n:::\n\n\n\n\n\n\n\n\n::: {.callout-tip}\n## Por que Bootstrap?\n\n**Efeitos indiretos** (a × b) não têm distribuição normal!\n\nBootstrap:\n- Reamostra dados 500× com reposição\n- Calcula a × b em cada amostra\n- IC baseado em distribuição empírica\n\n**Mais robusto** que método de Sobel para mediação.\n:::\n\n---\n\n### Resultados\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nparameterEstimates(fit_med1) %>%\n  dplyr::select(lhs, op, rhs, label, est, se, z,  pvalue, ci.lower, ci.upper) %>%\n  kable(\n    digits = 3,\n    col.names = c(\"VD\", \"←\", \"VI\", \"Param\", \"β\", \"EP\", \"z\", \"p\", \"IC_low\", \"IC_up\"),\n    caption = \"Estimativas do Modelo de Mediação 1\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Estimativas do Modelo de Mediação 1\n\n|VD            |←  |VI            |Param    |        β|      EP|      z|     p|   IC_low|    IC_up|\n|:-------------|:--|:-------------|:--------|--------:|-------:|------:|-----:|--------:|--------:|\n|Treinos       |~  |Sociabilidade |c_       |    0.605|   0.630|  0.961| 0.336|   -0.606|    1.985|\n|Treinos       |~  |IMC1          |b        |   -1.650|   1.013| -1.628| 0.104|   -3.501|    0.695|\n|IMC1          |~  |Sociabilidade |a        |    0.019|   0.051|  0.373| 0.709|   -0.093|    0.112|\n|Treinos       |~~ |Treinos       |         | 2327.025| 196.076| 11.868| 0.000| 1862.905| 2603.848|\n|IMC1          |~~ |IMC1          |         |   17.733|   2.932|  6.048| 0.000|   11.825|   23.446|\n|Sociabilidade |~~ |Sociabilidade |         |   65.601|   0.000|     NA|    NA|   65.601|   65.601|\n|Indireto      |:= |a*b           |Indireto |   -0.031|   0.100| -0.315| 0.753|   -0.211|    0.227|\n|Total         |:= |a*b+c_        |Total    |    0.574|   0.632|  0.907| 0.364|   -0.730|    1.905|\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n---\n\n### Interpretação - Modelo 1\n\n::: {.callout-warning}\n## 📊 Resultado: Mediação NÃO Confirmada\n\n**Caminhos:**\n- **a (Soc → IMC):** β = 0.019, p = 0.693 → **NS**\n- **b (IMC → Treino):** β = -1.650, p = 0.100 → **NS**\n- **c' (Soc → Treino direto):** β = 0.605, p = 0.360 → **NS**\n\n**Efeito Indireto:** β = -0.031, p = 0.717 → **NS**\n\n**Conclusão:**\nIMC **NÃO medeia** a relação entre Sociabilidade e Treinos.\n\n**Modelo teórico não se sustenta!**\n:::\n\n---\n\n### Diagrama do Modelo 1\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsemPaths(\n  fit_med1,\n  what = \"std\",\n  whatLabels = \"std\",\n  style = \"ram\",\n  layout = \"tree\",\n  rotation = 2,\n  sizeMan = 7,\n  edge.label.cex = 1,\n  label.cex = 1.2,\n  color = list(man = \"lightblue\")\n)\n```\n\n::: {.cell-output-display}\n![](lista_8_1_files/figure-html/unnamed-chunk-6-1.png){width=768}\n:::\n:::\n\n\n\n\n\n\n\n\n---\n\n## 🔍 Comparação: SEM vs Regressões Separadas\n\n### Regressão 1: Efeito Total (c)\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sociabilidade → Treinos (sem mediador)\nreg_total <- lm(Treinos ~ Sociabilidade, data = dados)\n\nsummary(reg_total)$coefficients %>%\n  kable(digits = 3, caption = \"Efeito Total (c)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Efeito Total (c)\n\n|              | Estimate| Std. Error| t value| Pr(>&#124;t&#124;)|\n|:-------------|--------:|----------:|-------:|------------------:|\n|(Intercept)   |   69.440|     14.164|   4.903|              0.000|\n|Sociabilidade |    0.574|      0.627|   0.915|              0.363|\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n---\n\n### Regressão 2: Caminho a\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sociabilidade → IMC\nreg_a <- lm(IMC1 ~ Sociabilidade, data = dados)\n\nsummary(reg_a)$coefficients %>%\n  kable(digits = 3, caption = \"Caminho a (X → M)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Caminho a (X → M)\n\n|              | Estimate| Std. Error| t value| Pr(>&#124;t&#124;)|\n|:-------------|--------:|----------:|-------:|------------------:|\n|(Intercept)   |   25.397|      1.224|  20.753|              0.000|\n|Sociabilidade |    0.019|      0.054|   0.351|              0.726|\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n---\n\n### Regressão 3: Caminhos b e c'\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# IMC + Sociabilidade → Treinos\nreg_bc <- lm(Treinos ~ IMC1 + Sociabilidade, data = dados)\n\nsummary(reg_bc)$coefficients %>%\n  kable(digits = 3, caption = \"Caminhos b (M → Y) e c' (X → Y direto)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Caminhos b (M → Y) e c' (X → Y direto)\n\n|              | Estimate| Std. Error| t value| Pr(>&#124;t&#124;)|\n|:-------------|--------:|----------:|-------:|------------------:|\n|(Intercept)   |  111.339|     33.598|   3.314|              0.001|\n|IMC1          |   -1.650|      1.201|  -1.374|              0.173|\n|Sociabilidade |    0.605|      0.625|   0.969|              0.335|\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n---\n\n### Diferença: SEM vs Regressões\n\n::: {.callout-important}\n## Por que SEM é Superior?\n\n**Regressões separadas:**\n- ✓ Estimam a, b, c'\n- ✗ **NÃO** calculam efeito indireto (a × b)\n- ✗ **NÃO** fornecem IC para mediação\n- ✗ Não testam significância da mediação\n\n**SEM (lavaan):**\n- ✓ Estima todos os caminhos\n- ✓ **Calcula efeito indireto** automaticamente\n- ✓ **Bootstrap IC** para a × b\n- ✓ **Teste formal** de mediação\n\n**Conclusão:** Use SEM para mediação!\n:::\n\n---\n\n## 🎯 Modelo 2: Idade como Mediador\n\n::: {.callout-tip}\n## Nova Hipótese\n\n**E se:** Sociabilidade → Idade → Treinos?\n\n(Hipótese pouco plausível, mas vamos testar!)\n:::\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_med2 <- \"\n  Treinos ~ c_*Sociabilidade + b*Idade\n  Idade ~ a*Sociabilidade\n  \n  Indireto := a*b\n  Total := a*b + c_\n\"\n\nfit_med2 <- sem(modelo_med2, data = dados, \n                se = \"bootstrap\", bootstrap = 500)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: lavaan->lav_model_nvcov_bootstrap():  \n   2 bootstrap runs failed or did not converge.\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n---\n\n### Resultados - Modelo 2\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nparameterEstimates(fit_med2) %>%\n  filter(op %in% c(\"~\", \":=\")) %>%\n  dplyr::select(lhs, op, rhs, label, est, se, z, pvalue, ci.lower, ci.upper) %>%\n  kable(digits = 3, caption = \"Mediação via Idade\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Mediação via Idade\n\n|lhs      |op |rhs           |label    |   est|    se|     z| pvalue| ci.lower| ci.upper|\n|:--------|:--|:-------------|:--------|-----:|-----:|-----:|------:|--------:|--------:|\n|Treinos  |~  |Sociabilidade |c_       | 0.485| 0.588| 0.826|  0.409|   -0.533|    1.734|\n|Treinos  |~  |Idade         |b        | 1.543| 0.507| 3.045|  0.002|    0.407|    2.446|\n|Idade    |~  |Sociabilidade |a        | 0.057| 0.106| 0.539|  0.590|   -0.152|    0.279|\n|Indireto |:= |a*b           |Indireto | 0.088| 0.173| 0.513|  0.608|   -0.221|    0.477|\n|Total    |:= |a*b+c_        |Total    | 0.574| 0.637| 0.901|  0.368|   -0.547|    1.894|\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n::: {.callout-note}\n## 📊 Resultado\n\n**Caminhos:**\n- **a (Soc → Idade):** p = 0.592 → **NS**\n- **b (Idade → Treino):** p = 0.001 → **Sig!**\n- **c':** p = 0.384 → **NS**\n\n**Efeito Indireto:** p = 0.605 → **NS**\n\n**Conclusão:**\nIdade prediz Treinos, mas **não medeia** efeito de Sociabilidade.\n:::\n\n---\n\n### Diagrama - Modelo 2\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsemPaths(\n  fit_med2,\n  what = \"std\",\n  whatLabels = \"std\",\n  style = \"ram\",\n  layout = \"tree\",\n  rotation = 2,\n  sizeMan = 7,\n  edge.label.cex = 1,\n  color = list(man = \"lightyellow\")\n)\n```\n\n::: {.cell-output-display}\n![](lista_8_1_files/figure-html/unnamed-chunk-12-1.png){width=768}\n:::\n:::\n\n\n\n\n\n\n\n\n---\n\n## 🎯 Modelo 3: IMC → Idade → Treinos\n\n::: {.callout-tip}\n## Terceira Hipótese\n\n**Explorando:** IMC → Idade → Treinos\n\n\"IMC influencia Treinos **através de** Idade\"\n:::\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_med3 <- \"\n  Treinos ~ c_*IMC1 + b*Idade\n  Idade ~ a*IMC1\n  \n  Indireto := a*b\n  Total := a*b + c_\n\"\n\nfit_med3 <- sem(modelo_med3, data = dados,\n                se = \"bootstrap\", bootstrap = 500)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: lavaan->lav_model_nvcov_bootstrap():  \n   3 bootstrap runs failed or did not converge.\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n---\n\n### Resultados - Modelo 3\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nparameterEstimates(fit_med3) %>%\n  filter(op %in% c(\"~\", \":=\")) %>%\n  dplyr::select(lhs, op, rhs, label, est, se, z, pvalue, ci.lower, ci.upper) %>%\n  kable(digits = 3, caption = \"Mediação: IMC → Idade → Treinos\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Mediação: IMC → Idade → Treinos\n\n|lhs      |op |rhs    |label    |    est|    se|      z| pvalue| ci.lower| ci.upper|\n|:--------|:--|:------|:--------|------:|-----:|------:|------:|--------:|--------:|\n|Treinos  |~  |IMC1   |c_       | -2.778| 0.979| -2.839|  0.005|   -4.669|   -0.735|\n|Treinos  |~  |Idade  |b        |  1.928| 0.493|  3.914|  0.000|    0.775|    2.788|\n|Idade    |~  |IMC1   |a        |  0.608| 0.212|  2.863|  0.004|    0.228|    1.080|\n|Indireto |:= |a*b    |Indireto |  1.171| 0.516|  2.271|  0.023|    0.317|    2.301|\n|Total    |:= |a*b+c_ |Total    | -1.607| 1.035| -1.553|  0.120|   -3.634|    0.590|\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n::: {.callout-tip}\n## ✓ Mediação Confirmada!\n\n**Caminhos:**\n- **a (IMC → Idade):** β = 0.608, p = 0.005 → **Sig!**\n- **b (Idade → Treino):** β = 1.928, p < 0.001 → **Sig!**\n- **c' (IMC → Treino direto):** β = -2.778, p = 0.006 → **Sig!**\n\n**Efeito Indireto:** β = 1.171, p = 0.030 → **Sig!**\n\n**Interpretação:**\n- IMC **negativamente** relacionado a Treinos (direto)\n- Mas IMC **positivamente** relacionado a Idade\n- E Idade **positivamente** relacionada a Treinos\n- **Mediação parcial:** Parte do efeito é indireto (via Idade)\n\n**Efeito supressor:** Indireto e direto têm **sinais opostos**!\n:::\n\n---\n\n### Diagrama - Modelo 3\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsemPaths(\n  fit_med3,\n  what = \"std\",\n  whatLabels = \"std\",\n  style = \"ram\",\n  layout = \"tree\",\n  rotation = 2,\n  sizeMan = 7,\n  edge.label.cex = 1,\n  color = list(man = \"lightcoral\")\n)\n```\n\n::: {.cell-output-display}\n![](lista_8_1_files/figure-html/unnamed-chunk-15-1.png){width=768}\n:::\n:::\n\n\n\n\n\n\n\n\n---\n\n## 📊 Análise Complementar: Pacote `mediation`\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Caminho a\nmodelo_a <- lm(Idade ~ IMC1, data = dados)\n\n# Caminhos b e c'\nmodelo_completo <- lm(Treinos ~ Idade + IMC1, data = dados)\n\n# Análise de mediação\nresultado_med <- mediate(\n  modelo_a,\n  modelo_completo,\n  treat = \"IMC1\",\n  mediator = \"Idade\",\n  boot = TRUE,\n  sims = 500\n)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRunning nonparametric bootstrap\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(resultado_med)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCausal Mediation Analysis \n\nNonparametric Bootstrap Confidence Intervals with the Percentile Method\n\n               Estimate 95% CI Lower 95% CI Upper p-value   \nACME            1.17100      0.31974      2.49958   0.004 **\nADE            -2.77816     -4.65810     -0.70602   0.012 * \nTotal Effect   -1.60717     -3.57212      0.64278   0.164   \nProp. Mediated -0.72861     -7.31420      6.49552   0.168   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nSample Size Used: 94 \n\n\nSimulations: 500 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n---\n\n### Visualização da Mediação\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmediate_plot(Treinos ~ Idade + IMC1, data = dados)\n```\n\n::: {.cell-output-display}\n![](lista_8_1_files/figure-html/unnamed-chunk-17-1.png){width=960}\n:::\n:::\n\n\n\n\n\n\n\n\n::: {.callout-tip}\n## 🔍 Interpretando o Gráfico\n\n**Painel 1 (esquerda):** IMC → Idade (caminho a)  \n**Painel 2 (direita):** Idade → Treinos (caminho b)  \n**Painel 3 (centro):** IMC → Treinos direto (c')\n\nLinhas mostram relação entre variáveis, controlando outras.\n:::\n\n---\n\n## 📊 Comparação dos Três Modelos\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extrair efeitos indiretos\nefeitos <- data.frame(\n  Modelo = c(\n    \"1: Soc → IMC → Treino\",\n    \"2: Soc → Idade → Treino\",\n    \"3: IMC → Idade → Treino\"\n  ),\n  Indireto_β = c(\n    parameterEstimates(fit_med1)[8, \"est\"],\n    parameterEstimates(fit_med2)[8, \"est\"],\n    parameterEstimates(fit_med3)[8, \"est\"]\n  ),\n  Indireto_p = c(\n    parameterEstimates(fit_med1)[8, \"pvalue\"],\n    parameterEstimates(fit_med2)[8, \"pvalue\"],\n    parameterEstimates(fit_med3)[8, \"pvalue\"]\n  )\n) %>%\n  mutate(\n    Significativo = ifelse(Indireto_p < 0.05, \"✓ Sim\", \"✗ Não\"),\n    across(where(is.numeric), ~round(., 3))\n  )\n\nkable(efeitos, caption = \"Comparação de Efeitos Indiretos\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Comparação de Efeitos Indiretos\n\n|Modelo                  | Indireto_β| Indireto_p|Significativo |\n|:-----------------------|----------:|----------:|:-------------|\n|1: Soc → IMC → Treino   |      0.574|      0.364|✗ Não         |\n|2: Soc → Idade → Treino |      0.574|      0.368|✗ Não         |\n|3: IMC → Idade → Treino |     -1.607|      0.120|✗ Não         |\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n::: {.callout-note}\n## 🏆 Modelo Vencedor\n\n**Modelo 3** é o único com mediação significativa!\n\n**Mensagem:** IMC afeta Treinos tanto:\n- **Diretamente** (negativamente)\n- **Indiretamente** via Idade (positivamente)\n\nSupressão: Efeito total pode ser enganoso!\n:::\n\n---\n\n## 🎓 Conceitos Avançados\n\n::: {.callout-tip collapse=\"true\"}\n## 📚 Tipos de Mediação\n\n**1. Mediação Completa**\n- c' = 0 (NS)\n- Todo efeito via M\n- Raro na prática\n\n**2. Mediação Parcial**\n- c' ≠ 0 (Sig)\n- Efeito direto + indireto\n- Mais comum\n\n**3. Mediação Inconsistente**\n- c' e (a×b) têm **sinais opostos**\n- \"Supressão\"\n- Modelo 3 é exemplo!\n\n**4. Não-Mediação**\n- a×b = 0 (NS)\n- M não explica X → Y\n- Modelos 1 e 2\n:::\n\n---\n\n::: {.callout-tip collapse=\"true\"}\n## 🗺️ Checklist de Mediação\n\n**1. Requisitos Teóricos**\n- [ ] X → M → Y faz sentido temporal\n- [ ] M é consequência de X (não pré-existente)\n- [ ] Mecanismo plausível\n\n**2. Requisitos Estatísticos**\n- [ ] Caminho a significativo (X → M)\n- [ ] Caminho b significativo (M → Y, controlando X)\n- [ ] Efeito indireto (a×b) significativo\n\n**3. Não é Necessário**\n- ✗ Efeito total (c) ser significativo\n- ✗ Baron & Kenny desatualizado!\n\n**4. Bootstrap**\n- [ ] Usar bootstrap (≥ 500 simulações)\n- [ ] IC não contém zero → mediação\n\n**5. Alternativas**\n- [ ] Considerar variáveis confundidoras\n- [ ] Testar mediação reversa\n- [ ] Análise de sensibilidade\n:::\n\n---\n\n## 📚 Material Complementar\n\n\n\n\n\n\n\n\n{{< video https://www.youtube.com/watch?v=NstttDePtcM title='SEM - Moderação e Mediação - Aula Prática #8.1' >}}\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n---\n\n### Recursos Adicionais\n\n::: {.callout-note collapse=\"true\"}\n## 📖 Aprofundamento\n\n**Tutoriais:**\n- [Simple Mediation in R](https://www.youtube.com/watch?v=nfQOCy9xMnk)\n- [Dustin Fife - Mediation with Visuals](https://www.youtube.com/watch?v=_4Fu8SZID2k)\n\n**Leituras:**\n- Hayes (2017). *Introduction to Mediation, Moderation*\n- MacKinnon (2008). *Introduction to Statistical Mediation Analysis*\n\n**Tópicos Avançados:**\n- Mediação múltipla (M1, M2...)\n- Mediação moderada\n- Mediação multinível\n- Análise de sensibilidade (Sensitivity analysis)\n:::\n\n---\n\n## 🔧 Informações de Sessão\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreport(sessionInfo())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalyses were conducted using the R Statistical language (version 4.4.2; R Core\nTeam, 2024) on Windows 11 x64 (build 26100), using the packages Matrix (version\n1.7.1; Bates D et al., 2024), effectsize (version 1.0.1; Ben-Shachar MS et al.,\n2020), semPlot (version 1.1.6; Epskamp S, 2022), flexplot (version 0.24.3;\nFife, D, 2022), mvtnorm (version 1.3.3; Genz A, Bretz F, 2009), lubridate\n(version 1.9.4; Grolemund G, Wickham H, 2011), parameters (version 0.28.3;\nLüdecke D et al., 2020), performance (version 0.15.2; Lüdecke D et al., 2021),\neasystats (version 0.7.5; Lüdecke D et al., 2022), see (version 0.12.0; Lüdecke\nD et al., 2021), insight (version 1.4.4; Lüdecke D et al., 2019), bayestestR\n(version 0.17.0; Makowski D et al., 2019), modelbased (version 0.13.1; Makowski\nD et al., 2025), report (version 0.6.3; Makowski D et al., 2023), correlation\n(version 0.8.8; Makowski D et al., 2022), tibble (version 3.3.1; Müller K,\nWickham H, 2026), datawizard (version 1.3.0; Patil I et al., 2022), foreign\n(version 0.8.87; R Core Team, 2024), lavaan (version 0.6.19; Rosseel Y, 2012),\nmediation (version 4.5.1; Tingley D et al., 2014), MASS (version 7.3.61;\nVenables WN, Ripley BD, 2002), ggplot2 (version 4.0.1; Wickham H, 2016),\nforcats (version 1.0.0; Wickham H, 2023), stringr (version 1.5.1; Wickham H,\n2023), tidyverse (version 2.0.0; Wickham H et al., 2019), dplyr (version 1.1.4;\nWickham H et al., 2023), purrr (version 1.0.4; Wickham H, Henry L, 2025), readr\n(version 2.1.5; Wickham H et al., 2024), tidyr (version 1.3.1; Wickham H et\nal., 2024), sandwich (version 3.1.1; Zeileis A et al., 2020) and kableExtra\n(version 1.4.0; Zhu H, 2024).\n\nReferences\n----------\n  - Bates D, Maechler M, Jagan M (2024). _Matrix: Sparse and Dense Matrix Classes\nand Methods_. R package version 1.7-1,\n<https://CRAN.R-project.org/package=Matrix>.\n  - Ben-Shachar MS, Lüdecke D, Makowski D (2020). \"effectsize: Estimation of\nEffect Size Indices and Standardized Parameters.\" _Journal of Open Source\nSoftware_, *5*(56), 2815. doi:10.21105/joss.02815\n<https://doi.org/10.21105/joss.02815>, <https://doi.org/10.21105/joss.02815>.\n  - Epskamp S (2022). _semPlot: Path Diagrams and Visual Analysis of Various SEM\nPackages' Output_. R package version 1.1.6,\n<https://CRAN.R-project.org/package=semPlot>.\n  - Fife, A. D (2022). \"Flexplot: Graphically-based data analysis.\"\n_Psychological Methods_, *27*(4), -19. <doi.org/10.1037/met0000424>.\n  - Genz A, Bretz F (2009). _Computation of Multivariate Normal and t\nProbabilities_, series Lecture Notes in Statistics. Springer-Verlag,\nHeidelberg. ISBN 978-3-642-01688-2.\n  - Grolemund G, Wickham H (2011). \"Dates and Times Made Easy with lubridate.\"\n_Journal of Statistical Software_, *40*(3), 1-25.\n<https://www.jstatsoft.org/v40/i03/>.\n  - Lüdecke D, Ben-Shachar M, Patil I, Makowski D (2020). \"Extracting, Computing\nand Exploring the Parameters of Statistical Models using R.\" _Journal of Open\nSource Software_, *5*(53), 2445. doi:10.21105/joss.02445\n<https://doi.org/10.21105/joss.02445>.\n  - Lüdecke D, Ben-Shachar M, Patil I, Waggoner P, Makowski D (2021).\n\"performance: An R Package for Assessment, Comparison and Testing of\nStatistical Models.\" _Journal of Open Source Software_, *6*(60), 3139.\ndoi:10.21105/joss.03139 <https://doi.org/10.21105/joss.03139>.\n  - Lüdecke D, Ben-Shachar M, Patil I, Wiernik B, Bacher E, Thériault R, Makowski\nD (2022). \"easystats: Framework for Easy Statistical Modeling, Visualization,\nand Reporting.\" _CRAN_. doi:10.32614/CRAN.package.easystats\n<https://doi.org/10.32614/CRAN.package.easystats>, R package,\n<https://easystats.github.io/easystats/>.\n  - Lüdecke D, Patil I, Ben-Shachar M, Wiernik B, Waggoner P, Makowski D (2021).\n\"see: An R Package for Visualizing Statistical Models.\" _Journal of Open Source\nSoftware_, *6*(64), 3393. doi:10.21105/joss.03393\n<https://doi.org/10.21105/joss.03393>.\n  - Lüdecke D, Waggoner P, Makowski D (2019). \"insight: A Unified Interface to\nAccess Information from Model Objects in R.\" _Journal of Open Source Software_,\n*4*(38), 1412. doi:10.21105/joss.01412 <https://doi.org/10.21105/joss.01412>.\n  - Makowski D, Ben-Shachar M, Lüdecke D (2019). \"bayestestR: Describing Effects\nand their Uncertainty, Existence and Significance within the Bayesian\nFramework.\" _Journal of Open Source Software_, *4*(40), 1541.\ndoi:10.21105/joss.01541 <https://doi.org/10.21105/joss.01541>,\n<https://joss.theoj.org/papers/10.21105/joss.01541>.\n  - Makowski D, Ben-Shachar M, Wiernik B, Patil I, Thériault R, Lüdecke D (2025).\n\"modelbased: An R package to make the most out of your statistical models\nthrough marginal means, marginal effects, and model predictions.\" _Journal of\nOpen Source Software_, *10*(109), 7969. doi:10.21105/joss.07969\n<https://doi.org/10.21105/joss.07969>,\n<https://joss.theoj.org/papers/10.21105/joss.07969>.\n  - Makowski D, Lüdecke D, Patil I, Thériault R, Ben-Shachar M, Wiernik B (2023).\n\"Automated Results Reporting as a Practical Tool to Improve Reproducibility and\nMethodological Best Practices Adoption.\" _CRAN_.\ndoi:10.32614/CRAN.package.report\n<https://doi.org/10.32614/CRAN.package.report>,\n<https://easystats.github.io/report/>.\n  - Makowski D, Wiernik B, Patil I, Lüdecke D, Ben-Shachar M (2022).\n\"correlation: Methods for Correlation Analysis.\" Version 0.8.3,\n<https://CRAN.R-project.org/package=correlation>. Makowski D, Ben-Shachar M,\nPatil I, Lüdecke D (2020). \"Methods and Algorithms for Correlation Analysis in\nR.\" _Journal of Open Source Software_, *5*(51), 2306. doi:10.21105/joss.02306\n<https://doi.org/10.21105/joss.02306>,\n<https://joss.theoj.org/papers/10.21105/joss.02306>.\n  - Müller K, Wickham H (2026). _tibble: Simple Data Frames_. R package version\n3.3.1, <https://CRAN.R-project.org/package=tibble>.\n  - Patil I, Makowski D, Ben-Shachar M, Wiernik B, Bacher E, Lüdecke D (2022).\n\"datawizard: An R Package for Easy Data Preparation and Statistical\nTransformations.\" _Journal of Open Source Software_, *7*(78), 4684.\ndoi:10.21105/joss.04684 <https://doi.org/10.21105/joss.04684>.\n  - R Core Team (2024). _foreign: Read Data Stored by 'Minitab', 'S', 'SAS',\n'SPSS', 'Stata', 'Systat', 'Weka', 'dBase', ..._. R package version 0.8-87,\n<https://CRAN.R-project.org/package=foreign>.\n  - R Core Team (2024). _R: A Language and Environment for Statistical\nComputing_. R Foundation for Statistical Computing, Vienna, Austria.\n<https://www.R-project.org/>.\n  - Rosseel Y (2012). \"lavaan: An R Package for Structural Equation Modeling.\"\n_Journal of Statistical Software_, *48*(2), 1-36. doi:10.18637/jss.v048.i02\n<https://doi.org/10.18637/jss.v048.i02>.\n  - Tingley D, Yamamoto T, Hirose K, Keele L, Imai K (2014). \"mediation: R\nPackage for Causal Mediation Analysis.\" _Journal of Statistical Software_,\n*59*(5), 1-38. <https://www.jstatsoft.org/v59/i05/>. Imai K, Keele L, Yamamoto\nT (2010). \"Identification, Inference, and Sensitivity Analysis for Causal\nMediation Effects.\" _Statistical Science_, *25*(1), 51-71.\n<https://imai.fas.harvard.edu/research/mediation.html>. Imai K, Keele L,\nTingley D (2010). \"A General Approach to Causal Mediation Analysis.\"\n_Psychological Methods_, *15*(4), 309-334.\n<https://imai.fas.harvard.edu/research/BaronKenny.html>. Imai K, Keele L,\nTingley D, Yamamoto T (2011). \"Unpacking the Black Box of Causality: Learning\nabout Causal Mechanisms from Experimental and Observational Studies.\" _American\nPolitical Science Review_, *105*(4), 765-789.\n<https://imai.fas.harvard.edu/research/mediationP.html>. Imai K, Yamamoto T\n(2013). \"Identification and Sensitivity Analysis for Multiple Causal\nMechanisms: Revisiting Evidence from Framing Experiments.\" _Political\nAnalysis_, *21*(2), 141-171.\n<https://imai.fas.harvard.edu/research/medsens.html>. Imai K, Keele L, Tingley\nD, Yamamoto T (2010). \"Causal Mediation Analysis Using R.\" In Vinod HD (ed.),\n_Advances in Social Science Research Using R_. Springer-Verlag, New York.\n  - Venables WN, Ripley BD (2002). _Modern Applied Statistics with S_, Fourth\nedition. Springer, New York. ISBN 0-387-95457-0,\n<https://www.stats.ox.ac.uk/pub/MASS4/>.\n  - Wickham H (2016). _ggplot2: Elegant Graphics for Data Analysis_.\nSpringer-Verlag New York. ISBN 978-3-319-24277-4,\n<https://ggplot2.tidyverse.org>.\n  - Wickham H (2023). _forcats: Tools for Working with Categorical Variables\n(Factors)_. R package version 1.0.0,\n<https://CRAN.R-project.org/package=forcats>.\n  - Wickham H (2023). _stringr: Simple, Consistent Wrappers for Common String\nOperations_. R package version 1.5.1,\n<https://CRAN.R-project.org/package=stringr>.\n  - Wickham H, Averick M, Bryan J, Chang W, McGowan LD, François R, Grolemund G,\nHayes A, Henry L, Hester J, Kuhn M, Pedersen TL, Miller E, Bache SM, Müller K,\nOoms J, Robinson D, Seidel DP, Spinu V, Takahashi K, Vaughan D, Wilke C, Woo K,\nYutani H (2019). \"Welcome to the tidyverse.\" _Journal of Open Source Software_,\n*4*(43), 1686. doi:10.21105/joss.01686 <https://doi.org/10.21105/joss.01686>.\n  - Wickham H, François R, Henry L, Müller K, Vaughan D (2023). _dplyr: A Grammar\nof Data Manipulation_. R package version 1.1.4,\n<https://CRAN.R-project.org/package=dplyr>.\n  - Wickham H, Henry L (2025). _purrr: Functional Programming Tools_. R package\nversion 1.0.4, <https://CRAN.R-project.org/package=purrr>.\n  - Wickham H, Hester J, Bryan J (2024). _readr: Read Rectangular Text Data_. R\npackage version 2.1.5, <https://CRAN.R-project.org/package=readr>.\n  - Wickham H, Vaughan D, Girlich M (2024). _tidyr: Tidy Messy Data_. R package\nversion 1.3.1, <https://CRAN.R-project.org/package=tidyr>.\n  - Zeileis A, Köll S, Graham N (2020). \"Various Versatile Variances: An\nObject-Oriented Implementation of Clustered Covariances in R.\" _Journal of\nStatistical Software_, *95*(1), 1-36. doi:10.18637/jss.v095.i01\n<https://doi.org/10.18637/jss.v095.i01>. Zeileis A (2004). \"Econometric\nComputing with HC and HAC Covariance Matrix Estimators.\" _Journal of\nStatistical Software_, *11*(10), 1-17. doi:10.18637/jss.v011.i10\n<https://doi.org/10.18637/jss.v011.i10>. Zeileis A (2006). \"Object-Oriented\nComputation of Sandwich Estimators.\" _Journal of Statistical Software_,\n*16*(9), 1-16. doi:10.18637/jss.v016.i09\n<https://doi.org/10.18637/jss.v016.i09>.\n  - Zhu H (2024). _kableExtra: Construct Complex Table with 'kable' and Pipe\nSyntax_. R package version 1.4.0,\n<https://CRAN.R-project.org/package=kableExtra>.\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n---\n\n::: {.callout-note appearance=\"simple\"}\n## 🎓 Resumo da Lista 8.1\n\nNesta lista você:\n\n✅ Compreendeu **mediação vs moderação**  \n✅ Especificou modelos de **mediação em lavaan**  \n✅ Calculou **efeitos indiretos** com bootstrap  \n✅ Interpretou **caminhos a, b, c, c'**  \n✅ Identificou **mediação parcial** e **supressão**  \n✅ Comparou **SEM vs regressões** separadas  \n✅ Usou **`mediation` package** para análise complementar  \n\n**Conceitos-chave:**\n- Mediação explica **como/por que** X afeta Y\n- Efeito indireto = a × b\n- Bootstrap para IC robusto\n- c = c' + (a × b)\n- Mediação parcial mais comum que completa\n- SEM superior a regressões separadas\n\n**Aplicações:**\n- Testar mecanismos psicológicos\n- Validar teorias causais\n- Identificar variáveis-alvo para intervenção\n- Análise de processos mediacionais\n\n**Armadilhas comuns:**\n- ✗ Assumir causalidade sem desenho apropriado\n- ✗ Ignorar confundidores\n- ✗ Mediação sem fundamentação teórica\n- ✗ Usar método Baron & Kenny desatualizado\n:::\n\n---\n\n::: {.callout-tip appearance=\"simple\"}\n## 🎉 Parabéns!\n\nVocê completou **todas as 10 listas** do tutorial de Modelos Estatísticos em R!\n\n**Jornada percorrida:**\n1. ✓ Introdução e GLM básico\n2. ✓ GEE com diferentes distribuições\n3. ✓ Matrizes de covariância (GMM)\n4. ✓ Modelos hierárquicos e ICC\n5. ✓ Modelos lineares generalizados\n6. ✓ Análise de sobrevida (Kaplan-Meier e Cox)\n7. ✓ Cox tempo-dependente\n8. ✓ Séries temporais (ARIMA)\n9. ✓ CFA e Path Analysis\n10. ✓ Mediação e Moderação\n\n**Próximos passos:**\n- Aplicar em seus dados reais\n- Consultar material complementar\n- Contribuir com feedback\n- Compartilhar conhecimento!\n\n**Bons estudos e sucesso em suas análises! 📊🚀**\n:::",
    "supporting": [
      "lista_8_1_files\\figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}